### ISSUE TITLE
Add Nextcloud specific server side encryption support

### ISSUE THREAD

**Issue by CitoplasmaX** [ONLYOFFICE/onlyoffice-owncloud#168] opened 2018-03-23 20:39 UTC
I will reference this topic of a colective that are using Nextcloud:
https://forum.disroot.org/t/what-do-you-think-about-use-onlyoffice-instead-collabora-online/3132

**Comment by alexanderonlyoffice** [comment] 2018-03-26 12:45
Hello @CitoplasmaX, please see issue #26 for answer.

**Comment by CitoplasmaX** [comment] 2018-03-26 20:07
Okay

**Comment by alexanderonlyoffice** [comment] 2018-03-27 09:44
Duplicate of #26

**Closed by alexanderonlyoffice** 2018-03-27 09:44 UTC
