### ISSUE TITLE
owncloud 9.1.4 + onlyoffice 1.0.2 + documentserver + 4.3 - Error when trying to connect (Not supported version)

### ISSUE THREAD

**Issue by maischroeder** [ONLYOFFICE/onlyoffice-owncloud#42] opened 2017-04-08 09:53 UTC
Hey Guys,

does anyone know how to fix this problem?

![bildschirmfoto 2017-04-08 um 11 52 03](https://cloud.githubusercontent.com/assets/27058968/24827838/f861c674-1c51-11e7-8b77-2b6b635a3a2b.png)

**Comment by JohnPerkin** [comment] 2017-04-10 08:27
Hello @maischroeder!
Please make sure that your Document Server is not earlier than 4.3. Open the link
`http://your_hostname/coauthoring/CommandService.ashx?c=version` and tell us the result.

**Comment by maischroeder** [comment] 2017-04-10 08:29
Hello @JohnPerkin !

I get this result from our Server 

> {"error":0,"version":"4.3.1.4"}

**Comment by JohnPerkin** [comment] 2017-04-10 08:59
Follow this [instruction](https://doc.owncloud.org/server/latest/admin_manual/configuration_server/logging_configuration.html) to set ownCloud's logs level to 0. Then send logs at support@onlyoffice.com

**Comment by maischroeder** [comment] 2017-04-10 20:39
@JohnPerkin done :)

**Comment by JohnPerkin** [comment] 2017-04-12 09:31
Hello @maischroeder 
Document Server works not only with GET, but also with POST requests. Try to make the following request:
POST `http://your_hostname/coauthoring/CommandService.ashx`
Content-Type: `application/json`
body: `{"c":"version"}`
The answer should be in JSON format: `{"error":0,"version":"4.3.1.4"} `

**Comment by maischroeder** [comment] 2017-04-12 10:02
Hello @JohnPerkin,
I changed the URL you send me per Mail, but now ill get "ONLYOFFICE not reached. Please contact admin"
If I type 

> http://mx1.mai-schroeder.de:8081/coauthoring/CommandService.ashx in Browser, Ill get an 

> {"error":1}
Error

**Comment by maischroeder** [comment] 2017-04-12 17:03
@JohnPerkin ,
Ill configured now SSL... I could now connect via owncloud. But now ill get the next Error :(
New URL is: https://ooffice.mai-schroeder.de

<img width="1352" alt="bildschirmfoto 2017-04-12 um 19 02 33" src="https://cloud.githubusercontent.com/assets/27058968/24969887/9fd261a8-1fb2-11e7-9328-a619550afc3c.png">

Is there anything i have to configure?

**Comment by JohnPerkin** [comment] 2017-04-13 08:01
Hello @maischroeder!
I suppose that the issue occurs because Document Server is still running by http. When you configure SSL for onwCloud server you need to switch ONLYOFFICE to https aw well.

**Comment by maischroeder** [comment] 2017-04-13 08:12
Hey @JohnPerkin,

i switched already both (owncloud & onyloffice) to SSL and configured it over HTTPS. On my test-owncloud it works, but not on our normal owncloud. Do you have an Idea?

**Comment by minh10huy** [comment] 2017-04-25 09:51
@maischroeder , I have the same problem. "**ONLYOFFICE not reached. Please contact admin**"
I build Owncloud and Onlyoffice a single server. Its run another port.

Could you guide me your resolved?

**Comment by raphson93** [comment] 2017-04-28 02:36
@minh10huy 

Hi, is your certificate for https document server self signed ?
If it was, you have to manually add the security exception in your browser.
Go your browser and put your document server url:
https://locahost:port

It will prompt you the security exception. 
Problem will resolve after you add the exception.

p/s: Please try in firefox :)

**Comment by JohnPerkin** [comment] 2017-06-09 09:15
Hello @maischroeder 
On the current moment is released integration app 1.0.4. Please update ownCloud/Nextcloud app and Document Server to the latest versions and tell us if it helped or did not.

**Comment by LinneyS** [comment] 2017-10-02 15:24
Hello @maischroeder
Could you please specify if the problem recurs or we can close the topic.

**Comment by onny** [comment] 2017-10-25 11:22
Strange, somethings seems to be wrong with my onlyoffice installation. I've compiled and installed it using my AUR package: https://aur.archlinux.org/packages/onlyoffice-documentserver/
If I access ``https://office.example.com/coauthoring/CommandService.ashx?c=version`` I get:
```
{"error":0,"version":"0.0.0.0"}
```
I have to add that I changed the default documentserver path and also the config file paths. But I tested it on an other server and it worked fine with the documentserver-integration-examples.

**Comment by agolybev** [comment] 2017-10-25 14:50
Hi @onny,
Please, add `PRODUCT_VERSION=4.3.0` enviroment varible before building Document Server. It'll setups correct product version for Document Server. Your problem occure because our owncloud plugin checks the minimum required version of Document Server. We are fixing it soon.

**Comment by onny** [comment] 2017-10-26 10:31
Thanks @agolybev, that fixed it for me 👍

**Closed** 2017-10-26 10:33 UTC

**Comment by amendrasathira** [comment] 2017-11-21 11:22
The path of "coauthoring/CommandService.ashx?c=version" is not working fo my onlyoffice server, so how can i fix it?
Please help me....

**Comment by alexanderonlyoffice** [comment] 2017-11-21 13:03
Hello @amendrasathira,

Could you please specify the problem in more details. What do you mean under the following:  

> is not working fo my onlyoffice server

Also specify the version of the document server.

**Comment by amendrasathira** [comment] 2017-11-21 16:25
Hi @alexanderonlyoffice 
Im install the onlyoffice Enterprise Edition and try to connect document server with owncloud. its getting bellow error : 
![1](https://user-images.githubusercontent.com/13369154/33083920-a4568ade-cf06-11e7-8e8f-aeaee44a1e34.JPG)

**Comment by alexanderonlyoffice** [comment] 2017-11-22 07:55
Hello @amendrasathira,

Please send us the screenshot of the document editing service address on your portal. Enter your portal -> Settings module -> Document Service subsection -> Screenshot of the settings.

Please specify also if you have any problems when editing documents on the portal. 

Try to add /ds-vpath/ to the address of the document server in OwnCloud administrator section (example: document_server_address/ds-vpath/)

**Comment by amendrasathira** [comment] 2017-11-22 09:05
Hi @alexanderonlyoffice 

Please find the Screenshot of the settings page.
![screenshot](https://user-images.githubusercontent.com/13369154/33118372-a3d3ef30-cf91-11e7-9e97-eb19bc32c64e.png)

 we dont have any problems when editing documents on the portal. both onlyoffice and owncloud servers are working fine separately .

**Comment by alexanderonlyoffice** [comment] 2017-11-22 12:27
Hello @amendrasathira,

Please add /ds-vpath/ to the address of the document server in OwnCloud administrator section (example: http://document_server_address/ds-vpath/), as we have mentioned in the previous message.

**Comment by amendrasathira** [comment] 2017-11-23 04:42
Hello @alexanderonlyoffice 
Still get that error..... :(

**Comment by alexanderonlyoffice** [comment] 2017-11-23 10:53
Hello @amendrasathira,

We have contacted you once in ZenDesk support system. Could you please send us screenshot of the administrator section of OwnCloud with the address of the document server you entered, so we can check the correctness of the address. Or you can send it to **support@onlyoffice.com**

**Comment by amendrasathira** [comment] 2017-11-23 14:08
Hello @alexanderonlyoffice 

Please find the screenshot of the administrator section of OwnCloud and OnlyOffice.

![1212](https://user-images.githubusercontent.com/13369154/33176620-b40baa88-d085-11e7-9b21-61bb8a916b94.JPG)
![22](https://user-images.githubusercontent.com/13369154/33176648-ca59630c-d085-11e7-8fab-2ea77b6721ab.png)
![33](https://user-images.githubusercontent.com/13369154/33176654-cf8fd22a-d085-11e7-837f-a0a7c8e103f7.png)

**Comment by alexanderonlyoffice** [comment] 2017-11-24 06:22
Hello @amendrasathira,

The address shown on the third screenshot is correct (http://office.lkdialog.lk/ds-vpath/). The problem is in token. Do the following: 

1) Enter container with document server;
2) Open default.json (etc/onlyoffice/documentserver/default.json) and copy token Secret and Header;
3) Open the config file /owncloud/config/config.php 
And add a section: 
```
'onlyoffice' =>
  array (
    "jwt_secret" => "****",
    "jwt_header" => "AuthorizationJwt"
  )
```
Secret and header should be the same, as they are in document server.

**Comment by amendrasathira** [comment] 2017-11-24 10:25
Hello @alexanderonlyoffice

Thank you very much for your support.
Currently i have completed 60% of this task. Right now i have came with an another error. 

screenshot of the administrator section of OwnCloud and default.json file of the OnlyOffice server.

![screenshot from 2017-11-24 12-37-53](https://user-images.githubusercontent.com/13369154/33206077-244a6434-d12f-11e7-9b88-2ac21a6f7d47.png)

screenshot of the administrator section of OwnCloud with New error massage.

![screenshot from 2017-11-24 14-28-01](https://user-images.githubusercontent.com/13369154/33206086-2bcdb314-d12f-11e7-8877-6b2327bd0b47.png)

screenshot of the OwnCloud document editing error.

![screenshot from 2017-11-24 14-28-50](https://user-images.githubusercontent.com/13369154/33206090-2f7b9df0-d12f-11e7-9c1c-3bbcc98e948f.png)

**Comment by alexanderonlyoffice** [comment] 2017-11-24 11:43
Hello @amendrasathira,

It seems that OwnCloud is not accessible for the document server. Please check the accessibility of the server with OwnCloud. Open the terminal on the server with ONLYOFFICE document server and do the following: 

1) Enter the container with document server: `sudo docker exec -it [container_id] bash`
2) Execute command: `wget  http://cloud.lkdialog.lk`

You can find the description of the problems [here](https://api.onlyoffice.com/editors/troubleshooting).

**Comment by amendrasathira** [comment] 2017-11-28 10:57
Hello @alexanderonlyoffice

I'm execute the command. 
![screenshot from 2017-11-28 16-18-07](https://user-images.githubusercontent.com/13369154/33316156-f5443ce6-d458-11e7-8e69-88125f1130bd.png)

But still i have the same issue..

**Comment by alexanderonlyoffice** [comment] 2017-11-28 11:07
Hello @amendrasathira,

Please send us logs of the OwnCloud to support@onlyoffice.com
