### ISSUE TITLE
Only-office and external storage SMB/CIFS

### ISSUE THREAD

**Issue by rikiki69** [ONLYOFFICE/onlyoffice-owncloud#163] opened 2018-03-15 11:37 UTC
Hi Everyone,

i've done a fresh install of nextcloud with only office with these versions :
Nextcloud 13.0.1 RC1
OnlyOffice 5.0.7CE
Nextcloud and Onlyoffice are in two different debian 9 VM

On standard directory and with shared files, everything works very well. 

I have an external CIFS/SMB storage, and users connect to it through nextcloud with their nextcloud session credentials. Navigation, download and sharing works very well. However, if i open a xlsx or docx files with onlyoffice and an another users (with others credentials), we can't see each others on the onlyoffice.
If i open the files in two different tab with the same account, the both see each others.

The biggest problem is that there is files versionning problem, as only office could send and erase different version when sending it to nextcloud.

Thanks !

**Comment by rikiki69** [comment] 2018-03-20 13:53
I've pushed the develop branch into my test server, opened a new file So i have this commit and have checked it. Same thing. Users don't show each others if they used different account

**Comment by rikiki69** [comment] 2018-03-27 07:24
Nobody has an idea ? It's a really great tool but this "bug" is really sad...

**Comment by alexanderonlyoffice** [comment] 2018-03-27 14:44
Duplicate of #132

**Closed by alexanderonlyoffice** 2018-03-27 14:44 UTC
