### ISSUE TITLE
"Save" doesnt save

### ISSUE THREAD

**Issue by zirkeltraining** [ONLYOFFICE/onlyoffice-owncloud#59] opened 2017-05-08 13:28 UTC
When editing collaboratively in fast mode (using nextcloud), it appears the file is never written back to nextcloud _until everyone ends their editing session_. 

Hitting the "save" button in the file menu pane does not seem to change that. 
That mean that if everyone keeps all their browser tabs open, then the file never gets saved to nextcloud... until something blows up.

For example, when the file becomes no longer accessible e.g. because the sharing link timed out etc, then all of the edits can't be written back and we've lost two peoples work at once.

At other times, we've had an issue when A had shared a file with B and C, then A was temporarily locked out of the LDAP server because of a few false logins on the mail account... meanwhile B and C kept working, and didn't notice that OO now failed to save the file... boom! two days worth of data entry gone.

Can you specify how the writeback behaviour is intended to be? Why doesn't "Save" seem to save the file on Nextcloud/Owncloud?

**Comment by Taste-IT** [comment] 2017-06-22 10:47
Hi,
same on my system with latest Nextcloud and OO-App. If i create a new file in NC und write something into this, close Tab after Document is saved, the Date in NC didnt updated. If i downloaded this file, the file doesnt have the changes. Actually i can only view existing files or write into it, but never see changes in NC. After last Update of NC i lost all Data i added in the last 4 weeks - very annoying...

**Comment by ibnpetr** [comment] 2017-06-23 09:04
@Taste-IT 
Hello, Could you please provide us with any information about the versions of the products installed on your server(s). We will try to reproduce the issue on our side.
Please describe your actions step by step.

> After last Update of NC i lost all Data i added in the last 4 weeks - very annoying...

Have you tried to contact NC to clear the situation? If you are sure that the problem is caused by ONLYOFFICE application please provide the details. I am sure that we are able to find a solution

**Comment by Taste-IT** [comment] 2017-06-23 12:08
I have this problem since i use OO in NC and noticed it first as i do an update of OO and all my data are gone. I have a parallel thread [link](https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/54) i think its an handling with the cert, but dont know where the problem is, NC or OO

**Comment by thfree** [comment] 2017-06-26 10:11
Аналогичная проблема не сохраняются в файл изменения после редактирования. 

nextcloud 12.0.0
onlyoffice-owncloud 1.1.2
onlyoffice-documetserver 4.3.6-2

**Comment by stuckj** [comment] 2017-11-10 05:30
I'm seeing this as well. Pressing "save" dismisses the menu, but does nothing. I _can_ export, however. In my case, I opened a .txt file in onlyoffice. My workaround wsa to simply export it in the format I wanted.

**Comment by informatico-madrid** [comment] 2017-12-18 16:35
Hi. Same problem here. any fix yet?

**Comment by thfree** [comment] 2017-12-18 19:20
Вообще сейчас у меня все работает.
In general now everything works for me.

nextcloud 12.0.4
onlyoffice: 1.1.6
onlyoffice-documetserver 4.3.6-2

**Comment by ivanoterouvigo** [comment] 2017-12-19 12:17
Hi all,
I had the same problem.
I wasn't able to update email of users.

Could you help me?
![set_email_001](https://user-images.githubusercontent.com/11814769/34156697-9fe2b27a-e4be-11e7-88d3-12bf9bc575a5.png)

I reviewed my email, in side of spam and other but I didn't see nothing with notifications of this mail.
What I need to do?

How can I review log of mails sended? Where .. ?

ONLYOFFICE | 1.1.4
ownCloud | 0.2.2

**Comment by hlorri** [comment] 2018-02-09 21:27
Same here.  "Save" does not save, however closing the OnlyOffice document tab (on all browsers where it is open) does.

onlyoffice-documentserver 5.0.7-38 (Debian, not in a docker)
nextcloud 12.0.5
postgresql 10+190

**Comment by alexanderonlyoffice** [comment] 2018-03-16 11:29
Hello,

Please do the following: 
Open browser's console (tab Console and then ab Network) and click on the Save button. Please send us screenshots if there is any information about the errors. 

Send us also logs of the document server and Nextcloud to support@onlyoffice.com with a note "for technical support" in email.

**Comment by alexanderonlyoffice** [comment] 2018-04-18 11:40
@e-tagirov, we are waiting for requested information.

**Comment by e-tagirov** [comment] 2018-04-18 14:04
@alexanderonlyoffice sent a couple of screenshots to the requested mail.

**Comment by DreamFlasher** [comment] 2018-11-29 22:50
Just lost 5 hours of work due to this bug. Looks like nobody is really caring about fixing data loss bugs here -.-

**Comment by alexanderonlyoffice** [comment] 2019-01-21 09:41
@Thoro, please specify the following information about the problem: 

1. Current version of Document Server;
2. Open browser's console (tab Console and then ab Network) and click on the Save button. Please send us screenshots if there is any information about the errors;
3. Have you tried to clear browser cache? 
4. Send us a screenshot of ONLYOFFICE integration app address settings.

**Comment by Thoro** [comment] 2019-01-21 09:51
1) Could you tell me how to find it? The url of the document server does not provide it
2) There's no error in the console tab, the websocket also doesn't send any values!
3) No, but saving in general works fine I believe, just not forcing by clicking the Save button
4) sent via email

**Comment by alexanderonlyoffice** [comment] 2019-01-21 10:02
@Thoro, we have received the screenshot and it seems that everything is fine with the address. Is there any error when clicking on the 'Save' button on ONLYOFFICE integration app address settings page? 

You may find the version of Document Server, if you open any file and click on the 'About' button on the left toolbar. 

Please note that if you enabled [force save](https://api.onlyoffice.com/editors/save#forcesave) feature in Document Server, it is not working in integration with Nextcloud. If this is not the issue you mentioned, please describe the scenario of how it can be reproduced.

**Comment by Thoro** [comment] 2019-01-21 10:11
@alexanderonlyoffice Ha, hard to find, currently it's 5.1.5

As far as I can see int he configs the force save feature is not activated.

Btw. is the plugin locking the file to stop people from overwriting the original via Desktop Sync?

**Comment by alexanderonlyoffice** [comment] 2019-01-21 10:36
@Thoro, could you please describe the issue you have more precisely, with screenshots or video if possible. 

>  Btw. is the plugin locking the file to stop people from overwriting the original via Desktop Sync?

There is no possibility to lock the files. If users have access permissions to the file in Nextcloud account, they will have the same permissions in Desktop Editors.

**Comment by alexanderonlyoffice** [comment] 2019-01-22 10:47
@Thoro, 

1. When you click on the 'Save' icon in editor changes made to the file are sent to the Document Server, but the new version of the file will be built only when the tab with editor is closed in browser (when the editing session is over). 

2. Please check if the Versions application is enabled in Nextcloud.

**Comment by Thoro** [comment] 2019-01-22 12:00
Oh!

1) is there an option to actually force from the client side a save back to nextcloud? As others said it happens constantly that the files stay open in some background tab

2) Versions is activated

**Comment by alexanderonlyoffice** [comment] 2019-01-23 13:46
@Thoro,  

> is there an option to actually force from the client side a save back to nextcloud? 

This is exactly force saving, which is not working in integration with Nextcloud due to some technical limitations, which cannot be solved at the moment.

> I mean, if people have the Nextcloud Desktop application, and they open the file in Excel, and therefore edit a old file which is not shared with anyone, and then save it to Nextcloud, they overwrite all the progress from the online editor, it would be good if in this case the file would be saves as a version and not overwrite the onlyoffice data.

We will check this case.

**Comment by KuenzelIT** [comment] 2019-03-06 10:18
> > is there an option to actually force from the client side a save back to nextcloud?
> 
> This is exactly force saving, which is not working in integration with Nextcloud due to some technical limitations, which cannot be solved at the moment.

So the owncloud integration can save back to the owncloud when all tabs are closed but not forced by some client action? This would be a really important feature.

The 'Save' button does not do anything at our instance, there is nothing on the console or in the network tab of the dev tools.

**Comment by alexanderonlyoffice** [comment] 2019-03-06 11:36
@KuenzelIT, 

> So the owncloud integration can save back to the owncloud when all tabs are closed but not forced by some client action? This would be a really important feature. 

Thank you for your feedback. As it was mentioned before there are some technical issues preventing us from implementing this feature. We are working on it. 

> The 'Save' button does not do anything at our instance, there is nothing on the console or in the network tab of the dev tools.

When you click on the 'Save' icon in editor changes made to the file are sent to the Document Server, but the new version of the file will be built only when the tab with editor is closed in browser (when the editing session is over).

**Comment by msumm** [comment] 2019-08-20 12:06
As pointed out [here](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/118) the problem might be hot-fixed by disabling the Versions App (in particular when the files to edit are located on an external storage).

**Comment by pricard32** [comment] 2019-11-20 22:43
Any progress on this? I've lost some important data... it seems to be long time since this tread are open...

**Comment by maxschons** [comment] 2020-01-15 15:50
Not being able to rely on downloading the up-to-date version of a document is a nightmare. This needs to be fixed ASAP.

**Comment by sinni800** [comment] 2020-01-23 02:49
This problem is so widespread that I even have it in Seafile too. Which makes me not too sure if this is a problem of this app and integration.

**Comment by KuenzelIT** [comment] 2020-01-23 10:40
Still waiting for this to be resolved. Any updates?

**Comment by Zegorax** [comment] 2020-02-18 10:03
I have the same issue using NextCloud. It is annoying to loose some data or to wait for everyone to close its browser tab.

Is there any progress about this ?

**Comment by sinni800** [comment] 2020-02-18 16:55
The part that actually solved it for me was the cronjob. I didnt have it on in the beginning and just used the automatic cronjobbing that works off things through requests. 

After I enabled native cronjobs (using actual cron to schedule them) the onlyoffice files always saved when the cronjob ran. So after all clients logged out of the file, on the next 5th minute it was saved.

**Comment by KuenzelIT** [comment] 2020-02-18 20:22
Can you at least describe the technical issues, so that we can understand the underlying problem? This issue is open for quite a while...

**Comment by sinni800** [comment] 2020-02-18 20:24
Files can be edited in OnlyOffice, but they never save back to Nextcloud is the issue. People who have it never really see any error messages anywhere usually, which is why they can't pinpoint anything helpful...

**Comment by Zegorax** [comment] 2020-02-18 20:26
> Can you at least describe the technical issues, so that we can understand the underlying problem? This issue is open for quite a while...

The problem is that when editing a file, the file is saved inside the Document Server, but not directly on the backend (NextCloud, OwnCloud, etc..). OnlyOffice saves the file only when every people closed its browser tab containing the file in edition.

It's a problem because there can be idle sessions, or backup processes that will not take the modified file since it is only inside Document Server. 

What would be great is like a timer / cronjob that saves the file every X minutes to the backend

**Comment by sinni800** [comment] 2020-02-18 20:28
> What would be great is like a timer / cronjob that saves the file every X minutes to the backend

I found for me that using native cronjobs (using actual OS cron running php-cli) will actually save the file when it runs. I have my cron running the Nextcloud jobs every 5 minutes, and on those 5 minute marks, it will reliably save OnlyOffice files... This is how it was fixed for me.

**Comment by Zegorax** [comment] 2020-02-18 20:29
>  It ONLY does it as long as no browser clients are connected to OnlyOffice for that file, though.

Yes, that does not solve the problem for me. What would be best is to save the file to the backend even if sessions are still connected

**Comment by sinni800** [comment] 2020-02-18 20:30
I see, that would be a nice feature indeed. I hope that can be made possible

**Comment by KuenzelIT** [comment] 2020-02-18 21:28
Sorry I did not made myself clear here. We have the exact same issue at our company. My question was pointed at the OnlyOffice Team and since the issue doesn't get solved I wanted to ask for specific details about WHY the issue is so hard to solve technically.

Some cronjob that saves the opened document every minute to Nextcloud would already help a lot. Also some button to push the document back to Nextcloud is also something that users expect. We had this issue with the "Save" Button, where everyone expected the document to be saved to Nextcloud while it was only saved to the document server (which happens anyways while editing...). The button seemed useless like that.

I just the issue gets solved soon. This is the only thing that stops a lot of people using Nextcloud + OnlyOffice for any serious stuff.

**Comment by jannishuebl** [comment] 2020-03-31 11:28
@KuenzelIT Did you got a reply? I also can not understand why this this so hard to solve. I don't have the time to dig into the code, but i assume it could be a one-liner.

**Comment by KuenzelIT** [comment] 2020-04-02 19:29
> @KuenzelIT Did you got a reply? I also can not understand why this this so hard to solve. I don't have the time to dig into the code, but i assume it could be a one-liner.

Unfortunately not.

**Comment by LAU10BAX** [comment] 2020-04-03 10:45
We have same issue by using the integrated application "$HOST/index.php/apps/documentserver_community/" This problem becomes nowadays more urgent, because of Corona so many more colleagues are forced to work from Home and we need to share some files safely, privately and within the browser.

Our System:
- Ubuntu LTS 18.04
- Nextcloud 18.0.3
- OnlyOffice 4.1.4

We've tried cronjobs, putting down session time of users and many more. We appreciate any help!

**Comment by philipp1992** [comment] 2020-04-15 21:28
we are also affected by this bug, exactly  the same behaviour. @alexanderonlyoffice  please keep us updated

**Comment by michaelflohr** [comment] 2020-06-25 20:58
We have integrated Nextcloud and OnlyOffice into our online platform. The problem that all tabs of all users of a document have to be closed first is a huge problem for us. We would be so grateful if there could be a solution for a regular forced save. Who can we turn to to solve the problem? Can you tell us what the problem is that for years the problem has not been solved? Perhaps we could also work together.

@alexanderonlyoffice @LinneyS

**Comment by sinni800** [comment] 2020-06-25 21:41
https://api.onlyoffice.com/editors/save

I've checked out this page of the API of OnlyOffice and there are a few interesting infos relating to this topic:

First of all, apparently automatic saving (back to the document storage) should happen within 10 seconds after editing has concluded. It doesn't define what that means, so I can't say if they mean "after the file was closed out" or something else.

Second, there is a "force saving" mode where one can either force save by a request to the document server (triggering the save callback to the document storage, nextcloud/owncloud in our case, instantly), or the force save will be triggered **5 minutes** (by default?) after (guessing here) nothing happened on the document anymore.

I'm almost guessing the force save is executed on the timeout for some reason, except the regular automatic saving. I don't have enough insight into the code here to even say how the regular saving would be triggered (hitting "save" apparently only saves to the document server)... I've tried to investigate it for a bit and haven't been coming up with anything good.

But there's an option that would attach the "save" button in the document to the "force save" function. Quoting from the page above:

> Enable the editorConfig.customization.forcesave mode setting it to true in the editor initialization configuration. In this case each time the user clicks the Save button, the forcesave will be done, and the forcesavetype parameter will have the 1 value when sending the request to the callback handler.

This could be configurable using the config gui in the nextcloud configuration for the onlyoffice app, the editor configs are applied here: https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/master/controller/editorcontroller.php#L847

```
$params["editorConfig"]["customization"]["forcesave "] = true;
```

**Comment by grueneedv** [comment] 2020-07-31 13:04
We have the same problem here. We have OnlyOffice Version 5.6.0, running within the docker solution "onlyoffice/documentserver-ie   latest".
Already edited the `/etc/onlyoffice/documentserver/local.json` and added `"autoAssembly": { "enable": true, "interval": "5m" }` as suggested here https://api.onlyoffice.com/editors/save and did a `/usr/bin/documentserver-generate-allfonts.sh` to trigger a restart within the docker container. No Help.
Tried the cron solution, so did a  `crontab -u www-data -e` adding `*/5 * * * * php -f /var/www/html/nextcloud/cron.php` and changed in admin settings from nextcloud the cron managment from AJAX to cron.  No Help.
Looked in the Browser Network analytics everything is fine:
![Save Problem](https://user-images.githubusercontent.com/17144683/89037478-d567bc80-d33e-11ea-9903-92481794a8ae.PNG)

So where to look next?

**Comment by mhl66** [comment] 2020-08-02 12:20
Since 2017, this bug exists, and it makes OnlyOffice UNUSABLE as a plugin for NextCloud. Anyone disagrees?

**Comment by michaelflohr** [comment] 2020-08-02 12:55
I heard that the bug was fixed with the last update. But we haven't been able to test it yet, because we integrated Nextcloud with OnlyOffice into an online platform and with the update the structure has changed as well, so we can only program the link properly again.

Has anyone tested the latest update to see if the bug is really fixed?

@mhl66 @grueneedv @sinni800 @philipp1992 @alexanderonlyoffice

**Comment by mhl66** [comment] 2020-08-02 14:46
In case you´re referring to the next update of Nextcloud (18.0.7): it is not. The last version of OnlyOffice in this version is displayed as 4.3.0.

**Comment by grueneedv** [comment] 2020-08-03 07:14
We're currently using 

- Nextcloud 18.0.3 
- 4.3.0 Plugin of OnlyOffice 
- 5.6.0 as OnlyOffice Version (within docker document-ie version).

This setup didn't worked on friday, but today after I restartet the nextcloud and the onlyoffice server completly. Will investigate further when saving files doesn't work again.

**Comment by mhl66** [comment] 2020-08-03 12:18
Clarification: Using Nextcloud 18.0.7 (=latest production version), 4.3.0 Plugin of OnlyOffice (latest) and Community Document Server of OnlyOffice, Version 0.1.7

INACCEPTABLE PROBLEM! Data lost! See https://github.com/nextcloud/documentserver_community/issues/12

**Comment by gcommit** [comment] 2020-09-07 12:58
We have the same problem .... 
NC version 19.0.2

can anyone help? I mean, we used collabora for years without bigger issues and swiched to OnlyOffice since it was build in to Nextcloud Hub and now changes are not written to file and the save button can't be used. 
![Bildschirmfoto 2020-09-07 um 14 58 36](https://user-images.githubusercontent.com/18714033/92390134-9d605000-f11a-11ea-8a34-af1f7f5bc4b3.png)

**Comment by LinneyS** [comment] 2020-09-29 07:12
Hi all!
Try _Keep intermediate versions when editing_ in settings in v6.0.1

**Closed by LinneyS** 2020-09-29 07:12 UTC
Labels: forcesave

**Comment by mhl66** [comment] 2020-09-30 13:37
> Hi all!
> Try _Keep intermediate versions when editing_ in settings in v6.0.1

Very funny - the newest version is 6.0.0 here.

The issue is still the same since 2017. Time to fix it.

**Comment by sinni800** [comment] 2020-09-30 13:38
I looked into the current code and the solution applied here is the same that I detailed in https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/59#issuecomment-649832269, but I concluded that it didn't work for me... Does this change work for anyone else?

**Comment by mhl66** [comment] 2020-09-30 13:39
To clarify: KEEP INTERMEDIATE VERSIONS WHEN EDITING (= "ZWISCHENVERSIONEN BEI DER BEARBEITUNG AUFBEWAHREN") does not change anything, it still does not "force save".

An office suite without saving?

**Comment by sinni800** [comment] 2020-09-30 13:39
I think the option is even weirdly named for what it does (enable force save)

**Comment by mhl66** [comment] 2020-09-30 13:41
Yeah, and the german translation is even more ridiculous. But anyway, IT DOES NOT WORK!

**Comment by 4001982248998** [comment] 2020-09-30 13:42
It seems to work for me, at least!

**Comment by philipp1992** [comment] 2020-09-30 13:50
Does not work for me. Fresh installation.

**Comment by ibnpetr** [comment] 2020-09-30 14:21
> An office suite without saving?

Cold you please contact us at support@onlyoffice.com (subject "OC saving issue") and we will analyze the issue.
We will need a temporary access to your environment.

**Comment by mhl66** [comment] 2020-09-30 14:25
You´re kidding? _"we will analyze the issue"_ is hardly appropriate, if you kindly read this thread from 2017 on.

Moreover, it´s sure to border on insolence to close this thread, referring to a version that is not even available for Nextcloud (6.0.1) by @LinneyS .

**Comment by ibnpetr** [comment] 2020-09-30 14:33
> You´re kidding? _"we will analyze the issue"_ is hardly appropriate, if you kindly read this thread from 2017 on.
> 
> Moreover, it´s sure to border on insolence to close this thread, referring to a version that is not even available for Nextcloud (6.0.1) by @LinneyS .

Don't you mind if I ask you again to send us access to your environment.
Looking forward to hearing from you.

**Comment by LinneyS** [comment] 2020-09-30 14:39
@mhl66 
> Very funny

Have you messed up the repository?

**Comment by mhl66** [comment] 2020-09-30 14:44
Indeed, the 6.0.0 is the newest version on https://github.com/ONLYOFFICE/onlyoffice-nextcloud. That´s what I was referring to. Please excuse the inappropriate comment "very funny". Nevertheless, it obviously (see issue section) does not work on both worlds - OWNCLOUD AND NEXTCLOUD for those users (probably the majority) using the document server module.

**Comment by LinneyS** [comment] 2020-10-01 13:55
@mhl66 
The analysis showed that Community Document Server does not work with forcesave.

Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by KuenzelIT** [comment] 2020-10-02 07:05
> Hi all!
> Try _Keep intermediate versions when editing_ in settings in v6.0.1

This was quite confusing since there is no version v6.0.1. You probably mean v6.0.0: [changelog](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/master/CHANGELOG.md#600)

**Comment by LinneyS** [comment] 2020-10-02 07:12
@KuenzelIT 
Have you messed up the repository?

**Comment by KuenzelIT** [comment] 2020-10-02 11:53
> @KuenzelIT
> Have you messed up the repository?

Seems like it. I just now noticed the owncloud/nextcloud difference in the repository name. I assume my brain already processes those words as being the same.
